#config_version=5

modes:
  - mode1

displays:
  default:
    width: 400
    height: 300

widget_styles:
  text_default:
    font_size: 21
    color: red
  bigStyle:
    font_size: 100
    halign: left

slides:
  slide1:
    - type: text
      text: HELLO
      style: bigStyle
      halign: right
    - type: text
      text: Default Style
      y: 100
  slide3:
    - type: text
      font_size: 30
      text: COLOR FROM DEFAULT STYLE
  slide4:
    - type: text
      text: TESTING INVALID STYLE
      style: bogus
  slide5:
    - type: text
      text: HELLO
      style: bigStyle
      font_size: 50

slide_player:
  slide1: slide1
  slide3: slide3
  slide4: slide4
  slide5: slide5
