# Travis is only used to test the Sphinx build and is configured to fail on
# bad links and references. The actual docs are published on RTD which has its
# own webhook and is not related to anything that travis does.
dist: trusty
sudo: required

matrix:
  fast_finish: true
  include:
   - os: linux
     env: LINUX=ubuntu:16.04
     sudo: required

services:
  - docker

before_install:
  - git clone --recursive --branch 0.54.x https://github.com/missionpinball/mpf.git _mpf;
  - git clone --recursive --branch 0.54.x https://github.com/missionpinball/mpf-mc.git _mpf-mc
  - git clone --branch dev https://github.com/missionpinball/mpf-debian-installer.git _mpf_installer;

script:
  - docker run -v $PWD:$PWD -w $PWD $LINUX /bin/sh -c "_mpf_installer/install-mpf-dependencies && _mpf_installer/install-mc-dependencies && apt-get install -y git xvfb && pip3 install -q -r requirements.txt && pip3 install _mpf/ && export DISPLAY=:99.0 && /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1280x720x24 -ac +extension GLX && export PYTHONPATH=$PYTHONPATH:$(pwd):$(pwd)/_mpf-mc && sphinx-build -nW -b html -d _build/doctrees . _build/html && sphinx-build -nW -b dummy -d _build/doctrees . _build/dummy -D use_mc=1";
