#config_version=5

displays:
  default:
    width: 800
    height: 600
  dmd:
    width: 128
    height: 32
widgets:
  right_dmd_widget:
    type: text
    text: "Right Widget"
    x: right
  left_dmd_widget:
    type: text
    text: "Left Widget"
    x: left
  top_dmd_widget:
    type: text
    text: "Top Widget"
    y: 100%
  bottom_dmd_widget:
    type: text
    text: "Bottom Widget"
    y: 0%
slides:
  container_slide:
    - type: display
      width: 640
      height: 160
      source_display: dmd
      effects:
        - type: dmd
    - type: text
      text: TRADITIONAL DMD TEST
      y: 200
    - type: rectangle
      width: 642
      height: 162
      color: gray
  dmd_slide:
    - type: text
      text: DMD TEXT
      anchor_x: center
      x: 128
      animations:
        show_slide:
          - property: x
            value: 10%
            duration: .25s
          - property: x
            value: 35%
            repeat: true
            duration: 250ms
    - type: rectangle
      width: 8
      height: 32
      color: ffffff
      x: 4
    - type: rectangle
      width: 8
      height: 32
      color: eeeeee
      x: 12
    - type: rectangle
      width: 8
      height: 32
      color: dddddd
      x: 20
    - type: rectangle
      width: 8
      height: 32
      color: cccccc
      x: 28
    - type: rectangle
      width: 8
      height: 32
      color: bbbbbb
      x: 36
    - type: rectangle
      width: 8
      height: 32
      color: aaaaaa
      x: 44
    - type: rectangle
      width: 8
      height: 32
      color: 999999
      x: 52
    - type: rectangle
      width: 8
      height: 32
      color: 888888
      x: 60
    - type: rectangle
      width: 8
      height: 32
      color: 777777
      x: 68
    - type: rectangle
      width: 8
      height: 32
      color: 666666
      x: 76
    - type: rectangle
      width: 8
      height: 32
      color: 555555
      x: 84
    - type: rectangle
      width: 8
      height: 32
      color: 444444
      x: 92
    - type: rectangle
      width: 8
      height: 32
      color: 333333
      x: 100
    - type: rectangle
      width: 8
      height: 32
      color: 222222
      x: 108
    - type: rectangle
      width: 8
      height: 32
      color: 111111
      x: 116
    - type: rectangle
      width: 8
      height: 32
      color: 000000
      x: 124

slide_player:
  container_slide: container_slide
  dmd_slide:
    dmd_slide:
      target: dmd

widget_player:
  position_widget_right:
    right_dmd_widget:
      target: dmd
  position_widget_left:
    left_dmd_widget:
      target: dmd
  position_widget_top:
    top_dmd_widget:
      target: dmd
  position_widget_bottom:
    bottom_dmd_widget:
      target: dmd
