#config_version=5
sound_system:
  buffer: 2048
  frequency: 44100
  channels: 2
  master_volume: 0.9
  tracks:
    playlist:
      type: playlist
      volume: 0.6
      crossfade_time: 2s

assets:
  sounds:
    default:
      load: preload
    playlist:
      load: preload
      track: playlist

sounds:
  drumbeat_7:
    file: 144554__kxtells__drumbeat-7.ogg
    events_when_played: drumbeat_7_played
    events_when_stopped: drumbeat_7_stopped
  hippie_ahead:
    file: 214473__diboz__hippeahead.ogg
    events_when_played: hippie_ahead_played
    events_when_stopped: hippie_ahead_stopped
  rainbow_disco_bears:
    file: 322071__edemson86__rainbowdiscobears.ogg
    events_when_played: rainbow_disco_bears_played
    events_when_stopped: rainbow_disco_bears_stopped
  dirty_grinding_beat_loop:
    file: 385984__blockh34d__dirty-grinding-beat-loop.ogg
    events_when_played: dirty_grinding_beat_loop_played
    events_when_stopped: dirty_grinding_beat_loop_stopped

playlists:
  attract_music:
    sounds: drumbeat_7, rainbow_disco_bears, dirty_grinding_beat_loop, hippie_ahead
    shuffle: False
    repeat: False
    events_when_played: attract_music_played
    events_when_stopped: attract_music_stopped
    events_when_looping: attract_music_looping
    events_when_sound_changed: attract_music_sound_changed
    events_when_sound_stopped: attract_music_sound_stopped

playlist_player:
  play_attract_music:
    playlist:
      playlist: attract_music
      action: play

  advance_playlist:
    playlist:
      action: advance

  stop_playlist:
    playlist:
      action: stop
