#config_version=5
sound_system:
  buffer: 2048
  frequency: 44100
  channels: 2
  master_volume: 0.9
  tracks:
    loops:
      type: sound_loop
      volume: 0.6
    music:
      volume: 0.5
      simultaneous_sounds: 1
    sfx:
      volume: 0.4
      simultaneous_sounds: 8
      preload: yes
    voice:
      volume: 0.6
      simultaneous_sounds: 1
      preload: yes

assets:
  sounds:
    default:
      load: preload
    loops:
      load: preload
      track: loops
    voice:
      load: preload
      track: voice
    sfx:
      load: preload
      track: sfx
    music:
      load: on_demand
      track: music
    playlist:
      load: on_demand
      track: sfx

sound_loop_sets:
  basic_beat:
    sound: kick
    volume: 0.5
    layers:
      - sound: hihat
        volume: 0.7
        initial_state: stop
      - sound: snare
        volume: 0.6
        initial_state: stop
      - sound: clap
        volume: 0.45
        initial_state: stop
    events_when_played: basic_beat_played
    events_when_looping: basic_beat_looping
    events_when_stopped: basic_beat_stopped, sound_loop_set_stopped
  basic_beat2:
    sound: kick2
    volume: 0.5
    layers:
      - sound: hihat
        volume: 0.7
      - sound: snare
        volume: 0.6
      - sound: clap
        volume: 0.4
        initial_state: stop
      - sound: bass_synth
        volume: 0.5
        initial_state: play

sound_loop_player:
  play_basic_beat:
    loops:
      action: play
      sound_loop_set: basic_beat
      queue: True
  add_hi_hats:
    loops:
      action: play_layer
      layer: 1
      queue: True
  stop_hi_hats:
    loops:
      action: stop_looping_layer
      layer: 1
  add_snare:
    loops:
      action: play_layer
      fade_in: 2s
      layer: 2
  add_claps:
    loops:
      action: play_layer
      layer: 3
      queue: True

  play_basic_beat2:
    loops:
      action: play
      sound_loop_set: basic_beat2
      queue: True
  add_bass_synth:
    loops:
      action: play_layer
      layer: 4
      queue: True
      fade_in: 3s
  fade_out_bass_synth:
    loops:
      action: stop_layer
      layer: 4
      fade_out: 4s

  stop_looping_current_loop:
    loops:
      action: stop_looping
  stop_current_loop:
    loops:
      action: stop
      fade_out: 1.5s
  reset_current_loop:
    loops:
      action: jump_to
      time: 0s

sound_player:
    play_sound_synthping: 210871_synthping
