#config_version=5

slides:
  slide1:
    - type: text
      text: widget1
      z: 100
    - type: text
      text: widget2
      z: 50
    - type: text
      text: widget3

slide_player:
  show_slide1:
    slide: slide1
