#config_version=5

displays:
  default:
    width: 400
    height: 300

slides:
  slide1:
    - type: points
      points: 50, 50, 75, 50, 100, 30, 200, 50, 68, 250
      pointsize: 3
    - type: line
      points: 0, 0, 100, 100, 100, 200
      color: 00ff00
      thickness: 10
      close: true
    - type: bezier
      points: 400, 300, 100, 100, 400, 0
      color: pink
      thickness: 5
    - type: triangle
      points: 400, 300, 200, 300, 400, 200
      color: red
    - type: quad
      points: 50, 50, 55, 70, 100, 75, 110, 45
      color: lightblue
    - type: ellipse
      width: 100
      height: 100
      color: purple
      angle_start: 0
      angle_end: 45
    - type: rectangle
      x: 250
      y: 125
      width: 200
      height: 100
      color: orange
      corner_radius: 30
    - type: rectangle
      x: 350
      y: 50
      width: 50
      height: 100
      color: blue

slide_player:
  slide1: slide1
