#config_version=5

mode:
  priority: 100

text_strings:
  greeting: HELLO FROM MODE 1

slides:
  text_string1_mode1:
    - type: text
      text: $greeting

slide_player:
  text_string1_mode1: text_string1_mode1
